version: '3'
output: prefixed
env:
  NEXT_TELEMETRY_DISABLED: '1'
  NPM_CONFIG_AUDIT: 'false'
  NPM_CONFIG_FUND: 'false'
  NPM_CONFIG_UPDATE_NOTIFIER: 'false'

  # Sentry doesn't work with Turbopack but we don't care because we don't use Sentry in local development and Turbopack
  # is only being used in local dev. This silences some warnings.
  SENTRY_SUPPRESS_TURBOPACK_WARNING: '1'

  # The OAuth Client Credentials Client ID for handling Google signins on this application (xngin-development-dc).
  # Use this during most development scenarios.
  NEXT_PUBLIC_XNGIN_GOOGLE_CLIENT_ID: '222213100775-qa1ajcrk48il70itcbdcvgr9ib5t08uf.apps.googleusercontent.com'

  # The OAuth Client Credentials Client ID for handling Google signins on this application (evidential-live).
  # Use this only when verifying production environments.
  # NEXT_PUBLIC_XNGIN_GOOGLE_CLIENT_ID: "314428509782-j8fgiq5dvoic01432s2bcu3isinc9kam.apps.googleusercontent.com"

  # The base URL of the xngin API server. Code will append the paths to the API endpoints (e.g. v1/m/apikeys, filters).
  NEXT_PUBLIC_XNGIN_API_BASE_URL: http://localhost:8000
  # The base URL of the xngin OIDC API.
  NEXT_PUBLIC_XNGIN_OIDC_BASE_URL: http://localhost:8000/v1/a/oidc
  # The URL that Google will redirect the user to when authentication is complete. This should be the public-facing URL
  # of the SPA and also should be set as a valid redirect URI in the Google Cloud config for this OAuth Client.
  NEXT_PUBLIC_XNGIN_OIDC_REDIRECT_URI: http://localhost:3000/
tasks:
  nodedeps:
    cmd: |
      command -v node >/dev/null 2>&1 || error "Node.js is not installed or not in PATH. Tip: install nvm then run 'nvm install'."
      CURRENT_NODE_VERSION=$(node --version | sed 's/v//')
      REQUIRED_NODE_VERSION=$(sed 's/v//' .nvmrc)
      echo Current node version: "${CURRENT_NODE_VERSION}"
      echo Desired node version: "${REQUIRED_NODE_VERSION}"
      if ! [[ "${CURRENT_NODE_VERSION}" =~ ^${REQUIRED_NODE_VERSION} ]]; then
        echo "Error: node --version of $CURRENT_NODE_VERSION does not match required version $REQUIRED_NODE_VERSION from .nvmrc"
        echo "Tip: Run 'nvm install' from the repo root to install and then run 'nvm use' to switch to the correct version."
        exit 1
      fi
      corepack pnpm install --frozen-lockfile
  start:
    desc: 'Starts the development server'
    interactive: true
    dotenv:
      - .env
    deps:
      - nodedeps
    cmd: |
      corepack pnpm run dev
  start-airplane:
    desc: "Like start, but runs the frontend in airplane mode. The UI will identify you as testing@example.com automatically."
    env:
      NEXT_PUBLIC_AIRPLANE_MODE: "true"
    interactive: true
    cmd: task start
  genapiclient:
    desc: 'Updates the generated API client from the apiserver running at http://localhost:8000'
    cmd: |
      curl --no-progress-meter --retry 10 --retry-connrefused --max-time 3 \
        -o /tmp/apispec.json http://localhost:8000/openapi.json
      jq . /tmp/apispec.json > openapi.json
      corepack pnpm exec orval --config orval.config.ts
      if [ $? -eq 0 ]; then
        task lint
      fi
  lint-next: corepack pnpm run lint
  lint-tsc: corepack pnpm exec tsc --noemit
  lint:
    deps:
      - lint-tsc
      - lint-next
    desc: 'Runs the NextJS-managed linter'
  build:
    desc: 'Production build of the NextJS application'
    cmd: corepack pnpm run build
  analyze:
    desc: 'Production build with bundle-analyzer reports written to .next/analyze/{client,nodejs,edge}.html'
    env:
      ANALYZE: 'true'
    cmd: corepack pnpm run build
  railway-build:
    desc: 'Builds the Docker image used by the Railway deployment.'
    cmd: docker build -t evidential-fe -f Dockerfile.railway .
  railway-run:
    desc: 'Runs the Docker image in a similar way to how Railway runs it.'
    interactive: true
    cmd: docker run --rm -it -p 3000:3000 evidential-fe
