/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Evidential Experiments API
 * OpenAPI spec version: 0.9.0
 */
export interface AddMemberToOrganizationRequest {
	email: string;
}

export interface AddWebhookToOrganizationRequest {
	type: "experiment.created";
	/** @maxLength 100 */
	name: string;
	/** @maxLength 500 */
	url: string;
}

export type AddWebhookToOrganizationResponseAuthToken = string | null;

export interface AddWebhookToOrganizationResponse {
	id: string;
	type: string;
	name: string;
	url: string;
	auth_token: AddWebhookToOrganizationResponseAuthToken;
}

export type AnyBanditDesignSpecInputExperimentType =
	(typeof AnyBanditDesignSpecInputExperimentType)[keyof typeof AnyBanditDesignSpecInputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnyBanditDesignSpecInputExperimentType = {
	cmab_online: "cmab_online",
	mab_online: "mab_online",
} as const;

export type AnyBanditDesignSpecInput =
	| (MABExperimentSpecInput & {
			experiment_type: AnyBanditDesignSpecInputExperimentType;
	  })
	| (CMABExperimentSpecInput & {
			experiment_type: AnyBanditDesignSpecInputExperimentType;
	  });

export type AnyBanditDesignSpecOutputExperimentType =
	(typeof AnyBanditDesignSpecOutputExperimentType)[keyof typeof AnyBanditDesignSpecOutputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnyBanditDesignSpecOutputExperimentType = {
	cmab_online: "cmab_online",
	mab_online: "mab_online",
} as const;

export type AnyBanditDesignSpecOutput =
	| (MABExperimentSpecOutput & {
			experiment_type: AnyBanditDesignSpecOutputExperimentType;
	  })
	| (CMABExperimentSpecOutput & {
			experiment_type: AnyBanditDesignSpecOutputExperimentType;
	  });

export type AnyFrequentistDesignSpecInputExperimentType =
	(typeof AnyFrequentistDesignSpecInputExperimentType)[keyof typeof AnyFrequentistDesignSpecInputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnyFrequentistDesignSpecInputExperimentType = {
	freq_online: "freq_online",
	freq_preassigned: "freq_preassigned",
} as const;

export type AnyFrequentistDesignSpecInput =
	| (PreassignedFrequentistExperimentSpecInput & {
			experiment_type: AnyFrequentistDesignSpecInputExperimentType;
	  })
	| (OnlineFrequentistExperimentSpecInput & {
			experiment_type: AnyFrequentistDesignSpecInputExperimentType;
	  });

export type AnyFrequentistDesignSpecOutputExperimentType =
	(typeof AnyFrequentistDesignSpecOutputExperimentType)[keyof typeof AnyFrequentistDesignSpecOutputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnyFrequentistDesignSpecOutputExperimentType = {
	freq_online: "freq_online",
	freq_preassigned: "freq_preassigned",
} as const;

export type AnyFrequentistDesignSpecOutput =
	| (PreassignedFrequentistExperimentSpecOutput & {
			experiment_type: AnyFrequentistDesignSpecOutputExperimentType;
	  })
	| (OnlineFrequentistExperimentSpecOutput & {
			experiment_type: AnyFrequentistDesignSpecOutputExperimentType;
	  });

export interface ApiKeySummary {
	/** @maxLength 64 */
	id: string;
	/** @maxLength 64 */
	datasource_id: string;
	/** @maxLength 64 */
	organization_id: string;
	/** @maxLength 100 */
	organization_name: string;
}

export type ApiOnlyDsnType =
	(typeof ApiOnlyDsnType)[keyof typeof ApiOnlyDsnType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiOnlyDsnType = {
	api_only: "api_only",
} as const;

export interface ApiOnlyDsn {
	type: ApiOnlyDsnType;
}

export type ArmArmId = string | null;

export type ArmArmDescription = string | null;

export type ArmArmWeight = ArmWeight | null;

export interface Arm {
	arm_id?: ArmArmId;
	/** @maxLength 100 */
	arm_name: string;
	arm_description?: ArmArmDescription;
	arm_weight?: ArmArmWeight;
}

export type ArmAnalysisArmId = string | null;

export type ArmAnalysisArmDescription = string | null;

export type ArmAnalysisArmWeight = ArmWeight | null;

export type ArmAnalysisPValue = number | null;

export type ArmAnalysisTStat = number | null;

export type ArmAnalysisStdError = number | null;

export type ArmAnalysisCiLower = number | null;

export type ArmAnalysisCiUpper = number | null;

export type ArmAnalysisMeanCiLower = number | null;

export type ArmAnalysisMeanCiUpper = number | null;

export interface ArmAnalysis {
	arm_id?: ArmAnalysisArmId;
	/** @maxLength 100 */
	arm_name: string;
	arm_description?: ArmAnalysisArmDescription;
	arm_weight?: ArmAnalysisArmWeight;
	estimate: number;
	p_value: ArmAnalysisPValue;
	t_stat: ArmAnalysisTStat;
	std_error: ArmAnalysisStdError;
	ci_lower?: ArmAnalysisCiLower;
	ci_upper?: ArmAnalysisCiUpper;
	mean_ci_lower?: ArmAnalysisMeanCiLower;
	mean_ci_upper?: ArmAnalysisMeanCiUpper;
	/** @minimum -1 */
	num_missing_values: number;
	is_baseline: boolean;
}

export type ArmBanditArmId = string | null;

export type ArmBanditArmDescription = string | null;

export type ArmBanditArmWeight = ArmWeight | null;

export type ArmBanditAlphaInit = number | null;

export type ArmBanditBetaInit = number | null;

export type ArmBanditMuInit = number | null;

export type ArmBanditSigmaInit = number | null;

export type ArmBanditAlpha = number | null;

export type ArmBanditBeta = number | null;

export type ArmBanditMu = number[] | null;

export type ArmBanditCovariance = number[][] | null;

export interface ArmBandit {
	arm_id?: ArmBanditArmId;
	/** @maxLength 100 */
	arm_name: string;
	arm_description?: ArmBanditArmDescription;
	arm_weight?: ArmBanditArmWeight;
	alpha_init?: ArmBanditAlphaInit;
	beta_init?: ArmBanditBetaInit;
	mu_init?: ArmBanditMuInit;
	sigma_init?: ArmBanditSigmaInit;
	alpha?: ArmBanditAlpha;
	beta?: ArmBanditBeta;
	mu?: ArmBanditMu;
	covariance?: ArmBanditCovariance;
}

export interface ArmSize {
	arm: Arm;
	size?: number;
}

/**
 */
export type ArmWeight = number;

export type AssignSummaryBalanceCheck = BalanceCheck | null;

export type AssignSummaryArmSizes = ArmSize[] | null;

export interface AssignSummary {
	balance_check?: AssignSummaryBalanceCheck;
	sample_size: number;
	arm_sizes?: AssignSummaryArmSizes;
}

export type AssignmentCreatedAt = string | null;

export type AssignmentStrata = Strata[] | null;

export type AssignmentObservedAt = string | null;

export type AssignmentOutcome = number | null;

export type AssignmentContextValues = number[] | null;

export interface Assignment {
	arm_id: string;
	/** @maxLength 64 */
	participant_id: string;
	/** @maxLength 100 */
	arm_name: string;
	created_at?: AssignmentCreatedAt;
	strata?: AssignmentStrata;
	observed_at?: AssignmentObservedAt;
	outcome?: AssignmentOutcome;
	context_values?: AssignmentContextValues;
}

export interface BalanceCheck {
	f_statistic: number;
	numerator_df: number;
	denominator_df: number;
	p_value: number;
	balance_ok: boolean;
}

export type BanditArmAnalysisArmId = string | null;

export type BanditArmAnalysisArmDescription = string | null;

export type BanditArmAnalysisArmWeight = ArmWeight | null;

export type BanditArmAnalysisAlphaInit = number | null;

export type BanditArmAnalysisBetaInit = number | null;

export type BanditArmAnalysisMuInit = number | null;

export type BanditArmAnalysisSigmaInit = number | null;

export type BanditArmAnalysisAlpha = number | null;

export type BanditArmAnalysisBeta = number | null;

export type BanditArmAnalysisMu = number[] | null;

export type BanditArmAnalysisCovariance = number[][] | null;

export interface BanditArmAnalysis {
	arm_id?: BanditArmAnalysisArmId;
	/** @maxLength 100 */
	arm_name: string;
	arm_description?: BanditArmAnalysisArmDescription;
	arm_weight?: BanditArmAnalysisArmWeight;
	alpha_init?: BanditArmAnalysisAlphaInit;
	beta_init?: BanditArmAnalysisBetaInit;
	mu_init?: BanditArmAnalysisMuInit;
	sigma_init?: BanditArmAnalysisSigmaInit;
	alpha?: BanditArmAnalysisAlpha;
	beta?: BanditArmAnalysisBeta;
	mu?: BanditArmAnalysisMu;
	covariance?: BanditArmAnalysisCovariance;
	prior_pred_mean: number;
	prior_pred_stdev: number;
	prior_pred_ci_upper: number;
	prior_pred_ci_lower: number;
	post_pred_mean: number;
	post_pred_stdev: number;
	post_pred_ci_upper: number;
	post_pred_ci_lower: number;
}

export type BanditExperimentAnalysisResponseType =
	(typeof BanditExperimentAnalysisResponseType)[keyof typeof BanditExperimentAnalysisResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BanditExperimentAnalysisResponseType = {
	bandit: "bandit",
} as const;

export type BanditExperimentAnalysisResponseContexts = number[] | null;

export interface BanditExperimentAnalysisResponse {
	type: BanditExperimentAnalysisResponseType;
	experiment_id: string;
	arm_analyses: BanditArmAnalysis[];
	n_outcomes: number;
	created_at: string;
	contexts?: BanditExperimentAnalysisResponseContexts;
}

export type BqDsnInputType =
	(typeof BqDsnInputType)[keyof typeof BqDsnInputType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BqDsnInputType = {
	bigquery: "bigquery",
} as const;

export type BqDsnInputCredentials = GcpServiceAccount | Hidden;

export interface BqDsnInput {
	type: BqDsnInputType;
	/**
	 * @minLength 6
	 * @maxLength 30
	 * @pattern ^[a-z0-9-]+$
	 */
	project_id: string;
	/**
	 * @minLength 1
	 * @maxLength 1024
	 * @pattern ^[a-zA-Z0-9_]+$
	 */
	dataset_id: string;
	credentials: BqDsnInputCredentials;
}

export type BqDsnOutputType =
	(typeof BqDsnOutputType)[keyof typeof BqDsnOutputType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BqDsnOutputType = {
	bigquery: "bigquery",
} as const;

export type BqDsnOutputCredentials = GcpServiceAccount | Hidden;

export interface BqDsnOutput {
	type: BqDsnOutputType;
	/**
	 * @minLength 6
	 * @maxLength 30
	 * @pattern ^[a-z0-9-]+$
	 */
	project_id: string;
	/**
	 * @minLength 1
	 * @maxLength 1024
	 * @pattern ^[a-zA-Z0-9_]+$
	 */
	dataset_id: string;
	credentials: BqDsnOutputCredentials;
}

export type CMABContextInputRequestContextInputs = ContextInput[] | null;

export interface CMABContextInputRequest {
	type?: "cmab_assignment";
	context_inputs: CMABContextInputRequestContextInputs;
}

export type CMABExperimentSpecInputExperimentType =
	(typeof CMABExperimentSpecInputExperimentType)[keyof typeof CMABExperimentSpecInputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CMABExperimentSpecInputExperimentType = {
	cmab_online: "cmab_online",
} as const;

export type CMABExperimentSpecInputDesignUrl = string | null;

export type CMABExperimentSpecInputContexts = Context[] | null;

export interface CMABExperimentSpecInput {
	experiment_type: CMABExperimentSpecInputExperimentType;
	/** @maxLength 100 */
	experiment_name: string;
	/** @maxLength 2000 */
	description: string;
	design_url?: CMABExperimentSpecInputDesignUrl;
	start_date: string;
	end_date: string;
	/**
	 * @minItems 2
	 * @maxItems 20
	 */
	arms: ArmBandit[];
	contexts?: CMABExperimentSpecInputContexts;
	prior_type?: PriorTypes;
	reward_type?: LikelihoodTypes;
}

export type CMABExperimentSpecOutputExperimentType =
	(typeof CMABExperimentSpecOutputExperimentType)[keyof typeof CMABExperimentSpecOutputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CMABExperimentSpecOutputExperimentType = {
	cmab_online: "cmab_online",
} as const;

export type CMABExperimentSpecOutputDesignUrl = string | null;

export type CMABExperimentSpecOutputContexts = Context[] | null;

export interface CMABExperimentSpecOutput {
	experiment_type: CMABExperimentSpecOutputExperimentType;
	/** @maxLength 100 */
	experiment_name: string;
	/** @maxLength 2000 */
	description: string;
	design_url?: CMABExperimentSpecOutputDesignUrl;
	start_date: string;
	end_date: string;
	/**
	 * @minItems 2
	 * @maxItems 20
	 */
	arms: ArmBandit[];
	contexts?: CMABExperimentSpecOutputContexts;
	prior_type?: PriorTypes;
	reward_type?: LikelihoodTypes;
}

export interface CallbackRequest {
	code: string;
	/**
	 * @minLength 43
	 * @maxLength 128
	 * @pattern ^[A-Za-z0-9._~-]+$
	 */
	code_verifier: string;
	/**
	 * @minLength 8
	 * @maxLength 128
	 */
	nonce: string;
}

export interface CallbackResponse {
	session_token: string;
}

export interface CallerIdentity {
	email: string;
	iss: string;
	sub: string;
	hd: string;
	is_privileged: boolean;
}

export type ColumnDeletedType =
	(typeof ColumnDeletedType)[keyof typeof ColumnDeletedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ColumnDeletedType = {
	column_deleted: "column_deleted",
} as const;

export interface ColumnDeleted {
	type: ColumnDeletedType;
	table_name: string;
	column_name: string;
}

export type ContextContextId = string | null;

export type ContextContextDescription = string | null;

export interface Context {
	context_id?: ContextContextId;
	/** @maxLength 100 */
	context_name: string;
	context_description?: ContextContextDescription;
	value_type?: ContextType;
}

export interface ContextInput {
	context_id: string;
	context_value: number;
}

export type ContextType = (typeof ContextType)[keyof typeof ContextType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContextType = {
	binary: "binary",
	"real-valued": "real-valued",
} as const;

export interface CreateApiKeyResponse {
	/** @maxLength 64 */
	id: string;
	datasource_id: string;
	key: string;
}

export interface CreateDatasourceRequest {
	/** @maxLength 64 */
	organization_id: string;
	name: string;
	dsn: DsnInput;
}

export interface CreateDatasourceResponse {
	/** @maxLength 64 */
	id: string;
}

export type CreateExperimentRequestPowerAnalyses = PowerResponseInput | null;

export interface CreateExperimentRequest {
	design_spec: DesignSpecInput;
	power_analyses?: CreateExperimentRequestPowerAnalyses;
	webhooks?: string[];
}

export type CreateExperimentResponseStoppedAssignmentsAt = string | null;

export type CreateExperimentResponseStoppedAssignmentsReason =
	StopAssignmentReason | null;

export type CreateExperimentResponsePowerAnalyses = PowerResponseOutput | null;

export type CreateExperimentResponseAssignSummary = AssignSummary | null;

export interface CreateExperimentResponse {
	experiment_id: string;
	datasource_id: string;
	state: ExperimentState;
	stopped_assignments_at: CreateExperimentResponseStoppedAssignmentsAt;
	stopped_assignments_reason: CreateExperimentResponseStoppedAssignmentsReason;
	design_spec: DesignSpecOutput;
	power_analyses: CreateExperimentResponsePowerAnalyses;
	assign_summary: CreateExperimentResponseAssignSummary;
	webhooks?: string[];
	decision?: string;
	impact?: Impact;
}

export interface CreateOrganizationRequest {
	/** @maxLength 100 */
	name: string;
}

export interface CreateOrganizationResponse {
	/** @maxLength 64 */
	id: string;
}

export interface CreateParticipantsTypeRequest {
	/** @maxLength 100 */
	participant_type: string;
	schema_def: ParticipantsSchemaInput;
}

export interface CreateParticipantsTypeResponse {
	/** @maxLength 100 */
	participant_type: string;
	schema_def: ParticipantsSchemaOutput;
}

export interface CreateSnapshotResponse {
	id: string;
}

export type DataType = (typeof DataType)[keyof typeof DataType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataType = {
	boolean: "boolean",
	character_varying: "character varying",
	uuid: "uuid",
	date: "date",
	integer: "integer",
	double_precision: "double precision",
	numeric: "numeric",
	timestamp_without_time_zone: "timestamp without time zone",
	timestamp_with_time_zone: "timestamp with time zone",
	bigint: "bigint",
	jsonb: "jsonb",
	json: "json",
	unknown: "unknown",
} as const;

export interface DatasourceSummary {
	/** @maxLength 64 */
	id: string;
	/** @maxLength 100 */
	name: string;
	driver: string;
	type: string;
	/** @maxLength 64 */
	organization_id: string;
	/** @maxLength 100 */
	organization_name: string;
}

export type DeleteExperimentDataRequestAssignments = boolean | null;

export type DeleteExperimentDataRequestSnapshots = boolean | null;

export interface DeleteExperimentDataRequest {
	assignments?: DeleteExperimentDataRequestAssignments;
	snapshots?: DeleteExperimentDataRequestSnapshots;
}

export type DesignSpecInput =
	| AnyFrequentistDesignSpecInput
	| AnyBanditDesignSpecInput;

export type DesignSpecOutput =
	| AnyFrequentistDesignSpecOutput
	| AnyBanditDesignSpecOutput;

export type DesignSpecMetricMetricPctChange = number | null;

export type DesignSpecMetricMetricTarget = number | null;

export type DesignSpecMetricIcc = number | null;

export type DesignSpecMetricAvgClusterSize = number | null;

export type DesignSpecMetricCv = number | null;

export type DesignSpecMetricMetricType = MetricType | null;

export type DesignSpecMetricMetricBaseline = number | null;

export type DesignSpecMetricMetricStddev = number | null;

export type DesignSpecMetricAvailableNonnullN = number | null;

export type DesignSpecMetricAvailableN = number | null;

export interface DesignSpecMetric {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	metric_pct_change?: DesignSpecMetricMetricPctChange;
	metric_target?: DesignSpecMetricMetricTarget;
	icc?: DesignSpecMetricIcc;
	avg_cluster_size?: DesignSpecMetricAvgClusterSize;
	cv?: DesignSpecMetricCv;
	metric_type?: DesignSpecMetricMetricType;
	metric_baseline?: DesignSpecMetricMetricBaseline;
	metric_stddev?: DesignSpecMetricMetricStddev;
	available_nonnull_n?: DesignSpecMetricAvailableNonnullN;
	available_n?: DesignSpecMetricAvailableN;
}

export type DesignSpecMetricRequestMetricPctChange = number | null;

export type DesignSpecMetricRequestMetricTarget = number | null;

export type DesignSpecMetricRequestIcc = number | null;

export type DesignSpecMetricRequestAvgClusterSize = number | null;

export type DesignSpecMetricRequestCv = number | null;

export interface DesignSpecMetricRequest {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	metric_pct_change?: DesignSpecMetricRequestMetricPctChange;
	metric_target?: DesignSpecMetricRequestMetricTarget;
	icc?: DesignSpecMetricRequestIcc;
	avg_cluster_size?: DesignSpecMetricRequestAvgClusterSize;
	cv?: DesignSpecMetricRequestCv;
}

export interface Drift {
	schema_diff: TableDiff[];
}

export type DsnInput = ApiOnlyDsn | PostgresDsn | BqDsnInput | RedshiftDsn;

export type DsnOutput = ApiOnlyDsn | PostgresDsn | BqDsnOutput | RedshiftDsn;

export type EventSummaryLink = string | null;

export type EventSummaryDetailsAnyOf = { [key: string]: unknown };

export type EventSummaryDetails = EventSummaryDetailsAnyOf | null;

export type EventSummaryStatusIcon =
	(typeof EventSummaryStatusIcon)[keyof typeof EventSummaryStatusIcon];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventSummaryStatusIcon = {
	success: "success",
	info: "info",
	failure: "failure",
} as const;

export interface EventSummary {
	id: string;
	created_at: string;
	type: string;
	summary: string;
	link?: EventSummaryLink;
	details: EventSummaryDetails;
	status_icon?: EventSummaryStatusIcon;
}

export type ExperimentAnalysisResponse =
	| FreqExperimentAnalysisResponse
	| BanditExperimentAnalysisResponse;

export type ExperimentConfigStoppedAssignmentsAt = string | null;

export type ExperimentConfigStoppedAssignmentsReason =
	StopAssignmentReason | null;

export type ExperimentConfigPowerAnalyses = PowerResponseOutput | null;

export type ExperimentConfigAssignSummary = AssignSummary | null;

export interface ExperimentConfig {
	experiment_id: string;
	datasource_id: string;
	state: ExperimentState;
	stopped_assignments_at: ExperimentConfigStoppedAssignmentsAt;
	stopped_assignments_reason: ExperimentConfigStoppedAssignmentsReason;
	design_spec: DesignSpecOutput;
	power_analyses: ExperimentConfigPowerAnalyses;
	assign_summary: ExperimentConfigAssignSummary;
	webhooks?: string[];
	decision?: string;
	impact?: Impact;
}

export type ExperimentState =
	(typeof ExperimentState)[keyof typeof ExperimentState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExperimentState = {
	designing: "designing",
	assigned: "assigned",
	abandoned: "abandoned",
	committed: "committed",
	aborted: "aborted",
} as const;

export type FieldChangedTypeType =
	(typeof FieldChangedTypeType)[keyof typeof FieldChangedTypeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FieldChangedTypeType = {
	column_changed_type: "column_changed_type",
} as const;

export interface FieldChangedType {
	type: FieldChangedTypeType;
	table_name: string;
	column_name: string;
	old_type: DataType;
	new_type: DataType;
}

export type FieldDescriptorExtraAnyOf = { [key: string]: string };

/**
 * @deprecated
 */
export type FieldDescriptorExtra = FieldDescriptorExtraAnyOf | null;

export interface FieldDescriptor {
	field_name: string;
	data_type: DataType;
	description?: string;
	is_unique_id?: boolean;
	is_strata?: boolean;
	is_filter?: boolean;
	is_metric?: boolean;
	/** @deprecated */
	extra?: FieldDescriptorExtra;
}

export interface FieldMetadata {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	data_type: DataType;
	/** @maxLength 2000 */
	description: string;
}

export interface FilterInput {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	relation: Relation;
	value: FilterValueTypes;
}

export interface FilterOutput {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	relation: Relation;
	value: FilterValueTypes;
}

export type FilterValueTypesAnyOfItem = string | null;

export type FilterValueTypesAnyOfTwoItem = boolean | null;

export type FilterValueTypes =
	| StrictInt[]
	| StrictFloat[]
	| FilterValueTypesAnyOfItem[]
	| FilterValueTypesAnyOfTwoItem[];

export type FreqExperimentAnalysisResponseType =
	(typeof FreqExperimentAnalysisResponseType)[keyof typeof FreqExperimentAnalysisResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FreqExperimentAnalysisResponseType = {
	freq: "freq",
} as const;

export type FreqExperimentAnalysisResponseNumMissingParticipants =
	| number
	| null;

export interface FreqExperimentAnalysisResponse {
	type: FreqExperimentAnalysisResponseType;
	experiment_id: string;
	metric_analyses: MetricAnalysis[];
	num_participants: number;
	num_missing_participants?: FreqExperimentAnalysisResponseNumMissingParticipants;
	created_at: string;
}

export interface GcpServiceAccount {
	type?: "serviceaccountinfo";
	content: GcpServiceAccountBlob;
}

/**
 * @minLength 4
 * @maxLength 8000
 */
export type GcpServiceAccountBlob = string;

export interface GetDatasourceResponse {
	/** @maxLength 64 */
	id: string;
	/** @maxLength 100 */
	name: string;
	dsn: DsnOutput;
	/** @maxLength 64 */
	organization_id: string;
	/** @maxLength 100 */
	organization_name: string;
}

export type GetExperimentAssignmentsResponseBalanceCheck = BalanceCheck | null;

export interface GetExperimentAssignmentsResponse {
	balance_check?: GetExperimentAssignmentsResponseBalanceCheck;
	experiment_id: string;
	sample_size: number;
	assignments: Assignment[];
}

export type GetExperimentForUiResponseExperimentSchema =
	ParticipantsSchemaOutput | null;

export interface GetExperimentForUiResponse {
	config: ExperimentConfig;
	experiment_schema: GetExperimentForUiResponseExperimentSchema;
}

export type GetExperimentResponseStoppedAssignmentsAt = string | null;

export type GetExperimentResponseStoppedAssignmentsReason =
	StopAssignmentReason | null;

export type GetExperimentResponsePowerAnalyses = PowerResponseOutput | null;

export type GetExperimentResponseAssignSummary = AssignSummary | null;

export interface GetExperimentResponse {
	experiment_id: string;
	datasource_id: string;
	state: ExperimentState;
	stopped_assignments_at: GetExperimentResponseStoppedAssignmentsAt;
	stopped_assignments_reason: GetExperimentResponseStoppedAssignmentsReason;
	design_spec: DesignSpecOutput;
	power_analyses: GetExperimentResponsePowerAnalyses;
	assign_summary: GetExperimentResponseAssignSummary;
	webhooks?: string[];
	decision?: string;
	impact?: Impact;
}

export type GetFiltersResponseDiscreteDistinctValues = string[] | null;

export interface GetFiltersResponseDiscrete {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	data_type: DataType;
	/**
	 * @minItems 1
	 * @maxItems 20
	 */
	relations: Relation[];
	/** @maxLength 2000 */
	description: string;
	distinct_values: GetFiltersResponseDiscreteDistinctValues;
}

export type GetFiltersResponseElement =
	| GetFiltersResponseNumericOrDate
	| GetFiltersResponseDiscrete;

export type GetFiltersResponseNumericOrDateMin =
	| string
	| string
	| number
	| number
	| null;

export type GetFiltersResponseNumericOrDateMax =
	| string
	| string
	| number
	| number
	| null;

export interface GetFiltersResponseNumericOrDate {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	data_type: DataType;
	/**
	 * @minItems 1
	 * @maxItems 20
	 */
	relations: Relation[];
	/** @maxLength 2000 */
	description: string;
	min: GetFiltersResponseNumericOrDateMin;
	max: GetFiltersResponseNumericOrDateMax;
}

export interface GetMetricsResponseElement {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	data_type: DataType;
	/** @maxLength 2000 */
	description: string;
}

export interface GetOrganizationResponse {
	/** @maxLength 64 */
	id: string;
	/** @maxLength 100 */
	name: string;
	users: UserSummary[];
	datasources: DatasourceSummary[];
}

export type GetParticipantAssignmentResponseAssignment = Assignment | null;

export interface GetParticipantAssignmentResponse {
	experiment_id: string;
	participant_id: string;
	assignment: GetParticipantAssignmentResponseAssignment;
}

export interface GetParticipantsTypeResponse {
	current: ParticipantsDef;
	proposed: ParticipantsDef;
	drift: Drift;
}

export interface GetSnapshotResponse {
	snapshot: Snapshot;
}

export interface GetStrataResponseElement {
	data_type: DataType;
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	/** @maxLength 2000 */
	description: string;
}

export type GetTurnArmJourneyMappingResponseArmToJourneys = {
	[key: string]: string;
};

export interface GetTurnArmJourneyMappingResponse {
	arm_to_journeys: GetTurnArmJourneyMappingResponseArmToJourneys;
}

export interface GetTurnConnectionResponse {
	token_preview: string;
}

export type GetTurnJourneysResponseJourneys = { [key: string]: string };

export interface GetTurnJourneysResponse {
	journeys: GetTurnJourneysResponseJourneys;
}

export interface HTTPExceptionError {
	detail: string;
}

export interface HTTPValidationError {
	detail?: ValidationError[];
}

export const HiddenValue = {
	type: "hidden",
} as const;
export type Hidden = typeof HiddenValue;

export type Impact = (typeof Impact)[keyof typeof Impact];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Impact = {
	high: "high",
	medium: "medium",
	low: "low",
	negative: "negative",
	unclear: "unclear",
	"": "",
} as const;

export interface InspectDatasourceResponse {
	tables: string[];
}

export interface InspectDatasourceTableResponse {
	primary_key_fields: string[];
	detected_unique_id_fields: string[];
	fields: FieldMetadata[];
}

export interface InspectParticipantTypesResponse {
	filters: GetFiltersResponseElement[];
	metrics: GetMetricsResponseElement[];
	strata: GetStrataResponseElement[];
}

export type LikelihoodTypes =
	(typeof LikelihoodTypes)[keyof typeof LikelihoodTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LikelihoodTypes = {
	binary: "binary",
	"real-valued": "real-valued",
} as const;

export interface ListApiKeysResponse {
	items: ApiKeySummary[];
}

export interface ListDatasourcesResponse {
	items: DatasourceSummary[];
}

export interface ListExperimentsResponse {
	items: ExperimentConfig[];
}

export interface ListOrganizationEventsResponse {
	next_page_token?: string;
	items: EventSummary[];
}

export interface ListOrganizationsResponse {
	items: OrganizationSummary[];
}

export interface ListParticipantsTypeResponse {
	items: ParticipantsDef[];
	has_hidden: boolean;
}

export type ListSnapshotsResponseLatestFailure = string | null;

export interface ListSnapshotsResponse {
	next_page_token?: string;
	items: Snapshot[];
	latest_failure: ListSnapshotsResponseLatestFailure;
}

export interface ListWebhooksResponse {
	items: WebhookSummary[];
}

export type MABExperimentSpecInputExperimentType =
	(typeof MABExperimentSpecInputExperimentType)[keyof typeof MABExperimentSpecInputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MABExperimentSpecInputExperimentType = {
	mab_online: "mab_online",
} as const;

export type MABExperimentSpecInputDesignUrl = string | null;

export type MABExperimentSpecInputContexts = Context[] | null;

export interface MABExperimentSpecInput {
	experiment_type: MABExperimentSpecInputExperimentType;
	/** @maxLength 100 */
	experiment_name: string;
	/** @maxLength 2000 */
	description: string;
	design_url?: MABExperimentSpecInputDesignUrl;
	start_date: string;
	end_date: string;
	/**
	 * @minItems 2
	 * @maxItems 20
	 */
	arms: ArmBandit[];
	contexts?: MABExperimentSpecInputContexts;
	prior_type?: PriorTypes;
	reward_type?: LikelihoodTypes;
}

export type MABExperimentSpecOutputExperimentType =
	(typeof MABExperimentSpecOutputExperimentType)[keyof typeof MABExperimentSpecOutputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MABExperimentSpecOutputExperimentType = {
	mab_online: "mab_online",
} as const;

export type MABExperimentSpecOutputDesignUrl = string | null;

export type MABExperimentSpecOutputContexts = Context[] | null;

export interface MABExperimentSpecOutput {
	experiment_type: MABExperimentSpecOutputExperimentType;
	/** @maxLength 100 */
	experiment_name: string;
	/** @maxLength 2000 */
	description: string;
	design_url?: MABExperimentSpecOutputDesignUrl;
	start_date: string;
	end_date: string;
	/**
	 * @minItems 2
	 * @maxItems 20
	 */
	arms: ArmBandit[];
	contexts?: MABExperimentSpecOutputContexts;
	prior_type?: PriorTypes;
	reward_type?: LikelihoodTypes;
}

export interface MessageError {
	message: string;
}

export interface MetricAnalysis {
	metric_name: string;
	metric: DesignSpecMetricRequest;
	arm_analyses: ArmAnalysis[];
}

export type MetricPowerAnalysisInputTargetN = number | null;

export type MetricPowerAnalysisInputSufficientN = boolean | null;

export type MetricPowerAnalysisInputTargetPossible = number | null;

export type MetricPowerAnalysisInputPctChangePossible = number | null;

export type MetricPowerAnalysisInputPctChangeWithDesiredN = number | null;

export type MetricPowerAnalysisInputMsg = MetricPowerAnalysisMessage | null;

export type MetricPowerAnalysisInputNumClustersTotal = number | null;

export type MetricPowerAnalysisInputClustersPerArm = number[] | null;

export type MetricPowerAnalysisInputNPerArm = number[] | null;

export type MetricPowerAnalysisInputDesignEffect = number | null;

export type MetricPowerAnalysisInputEffectiveSampleSize = number | null;

export interface MetricPowerAnalysisInput {
	metric_spec: DesignSpecMetric;
	target_n?: MetricPowerAnalysisInputTargetN;
	sufficient_n?: MetricPowerAnalysisInputSufficientN;
	target_possible?: MetricPowerAnalysisInputTargetPossible;
	pct_change_possible?: MetricPowerAnalysisInputPctChangePossible;
	pct_change_with_desired_n?: MetricPowerAnalysisInputPctChangeWithDesiredN;
	msg?: MetricPowerAnalysisInputMsg;
	num_clusters_total?: MetricPowerAnalysisInputNumClustersTotal;
	clusters_per_arm?: MetricPowerAnalysisInputClustersPerArm;
	n_per_arm?: MetricPowerAnalysisInputNPerArm;
	design_effect?: MetricPowerAnalysisInputDesignEffect;
	effective_sample_size?: MetricPowerAnalysisInputEffectiveSampleSize;
}

export type MetricPowerAnalysisOutputTargetN = number | null;

export type MetricPowerAnalysisOutputSufficientN = boolean | null;

export type MetricPowerAnalysisOutputTargetPossible = number | null;

export type MetricPowerAnalysisOutputPctChangePossible = number | null;

export type MetricPowerAnalysisOutputPctChangeWithDesiredN = number | null;

export type MetricPowerAnalysisOutputMsg = MetricPowerAnalysisMessage | null;

export type MetricPowerAnalysisOutputNumClustersTotal = number | null;

export type MetricPowerAnalysisOutputClustersPerArm = number[] | null;

export type MetricPowerAnalysisOutputNPerArm = number[] | null;

export type MetricPowerAnalysisOutputDesignEffect = number | null;

export type MetricPowerAnalysisOutputEffectiveSampleSize = number | null;

export interface MetricPowerAnalysisOutput {
	metric_spec: DesignSpecMetric;
	target_n?: MetricPowerAnalysisOutputTargetN;
	sufficient_n?: MetricPowerAnalysisOutputSufficientN;
	target_possible?: MetricPowerAnalysisOutputTargetPossible;
	pct_change_possible?: MetricPowerAnalysisOutputPctChangePossible;
	pct_change_with_desired_n?: MetricPowerAnalysisOutputPctChangeWithDesiredN;
	msg?: MetricPowerAnalysisOutputMsg;
	num_clusters_total?: MetricPowerAnalysisOutputNumClustersTotal;
	clusters_per_arm?: MetricPowerAnalysisOutputClustersPerArm;
	n_per_arm?: MetricPowerAnalysisOutputNPerArm;
	design_effect?: MetricPowerAnalysisOutputDesignEffect;
	effective_sample_size?: MetricPowerAnalysisOutputEffectiveSampleSize;
}

export type MetricPowerAnalysisMessageValuesAnyOf = {
	[key: string]: number | number;
};

export type MetricPowerAnalysisMessageValues =
	MetricPowerAnalysisMessageValuesAnyOf | null;

export interface MetricPowerAnalysisMessage {
	type: MetricPowerAnalysisMessageType;
	msg: string;
	source_msg: string;
	values?: MetricPowerAnalysisMessageValues;
	high_cluster_variation?: boolean;
}

export type MetricPowerAnalysisMessageType =
	(typeof MetricPowerAnalysisMessageType)[keyof typeof MetricPowerAnalysisMessageType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetricPowerAnalysisMessageType = {
	sufficient: "sufficient",
	insufficient: "insufficient",
	no_baseline: "no baseline",
	no_available_n: "no available n",
	zero_effect_size: "zero effect size",
	zero_variation: "zero variation",
} as const;

export type MetricType = (typeof MetricType)[keyof typeof MetricType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetricType = {
	binary: "binary",
	numeric: "numeric",
} as const;

export interface OnlineAssignmentWithFiltersRequest {
	/** List of participant properties to potentially filter against the experiment's filters. */
	properties: ParticipantProperty[];
}

export type OnlineFrequentistExperimentSpecInputExperimentType =
	(typeof OnlineFrequentistExperimentSpecInputExperimentType)[keyof typeof OnlineFrequentistExperimentSpecInputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnlineFrequentistExperimentSpecInputExperimentType = {
	freq_online: "freq_online",
} as const;

export type OnlineFrequentistExperimentSpecInputDesignUrl = string | null;

export type OnlineFrequentistExperimentSpecInputClusterKey = string | null;

export type OnlineFrequentistExperimentSpecInputDesiredN = number | null;

export interface OnlineFrequentistExperimentSpecInput {
	experiment_type: OnlineFrequentistExperimentSpecInputExperimentType;
	/** @maxLength 100 */
	experiment_name: string;
	/** @maxLength 2000 */
	description: string;
	design_url?: OnlineFrequentistExperimentSpecInputDesignUrl;
	start_date: string;
	end_date: string;
	/**
	 * @minItems 2
	 * @maxItems 20
	 */
	arms: Arm[];
	/** @maxLength 100 */
	table_name: string;
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	primary_key: string;
	cluster_key?: OnlineFrequentistExperimentSpecInputClusterKey;
	/** @maxItems 150 */
	strata: Stratum[];
	/**
	 * @minItems 1
	 * @maxItems 150
	 */
	metrics: DesignSpecMetricRequest[];
	/** @maxItems 20 */
	filters: FilterInput[];
	desired_n?: OnlineFrequentistExperimentSpecInputDesiredN;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	power?: number;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	alpha?: number;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	fstat_thresh?: number;
}

export type OnlineFrequentistExperimentSpecOutputExperimentType =
	(typeof OnlineFrequentistExperimentSpecOutputExperimentType)[keyof typeof OnlineFrequentistExperimentSpecOutputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnlineFrequentistExperimentSpecOutputExperimentType = {
	freq_online: "freq_online",
} as const;

export type OnlineFrequentistExperimentSpecOutputDesignUrl = string | null;

export type OnlineFrequentistExperimentSpecOutputClusterKey = string | null;

export type OnlineFrequentistExperimentSpecOutputDesiredN = number | null;

export interface OnlineFrequentistExperimentSpecOutput {
	experiment_type: OnlineFrequentistExperimentSpecOutputExperimentType;
	/** @maxLength 100 */
	experiment_name: string;
	/** @maxLength 2000 */
	description: string;
	design_url?: OnlineFrequentistExperimentSpecOutputDesignUrl;
	start_date: string;
	end_date: string;
	/**
	 * @minItems 2
	 * @maxItems 20
	 */
	arms: Arm[];
	/** @maxLength 100 */
	table_name: string;
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	primary_key: string;
	cluster_key?: OnlineFrequentistExperimentSpecOutputClusterKey;
	/** @maxItems 150 */
	strata: Stratum[];
	/**
	 * @minItems 1
	 * @maxItems 150
	 */
	metrics: DesignSpecMetricRequest[];
	/** @maxItems 20 */
	filters: FilterOutput[];
	desired_n?: OnlineFrequentistExperimentSpecOutputDesiredN;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	power?: number;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	alpha?: number;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	fstat_thresh?: number;
}

export interface OrganizationSummary {
	/** @maxLength 64 */
	id: string;
	/** @maxLength 100 */
	name: string;
}

export interface ParticipantProperty {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	value: PropertyValueTypes;
}

export interface ParticipantsDef {
	table_name: string;
	fields: FieldDescriptor[];
	type: "schema";
	participant_type: string;
	hidden?: boolean;
}

export interface ParticipantsSchemaInput {
	table_name: string;
	fields: FieldDescriptor[];
}

export interface ParticipantsSchemaOutput {
	table_name: string;
	fields: FieldDescriptor[];
}

export type PostgresDsnType =
	(typeof PostgresDsnType)[keyof typeof PostgresDsnType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostgresDsnType = {
	postgres: "postgres",
} as const;

export type PostgresDsnPassword = RevealedStr | Hidden;

export type PostgresDsnSslmode =
	(typeof PostgresDsnSslmode)[keyof typeof PostgresDsnSslmode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostgresDsnSslmode = {
	disable: "disable",
	require: "require",
	"verify-ca": "verify-ca",
	"verify-full": "verify-full",
} as const;

export type PostgresDsnSearchPath = string | null;

export interface PostgresDsn {
	type: PostgresDsnType;
	host: string;
	/**
	 * @minimum 1024
	 * @maximum 65535
	 */
	port: number;
	user: string;
	password: PostgresDsnPassword;
	dbname: string;
	sslmode: PostgresDsnSslmode;
	search_path: PostgresDsnSearchPath;
}

export interface PowerRequest {
	design_spec: AnyFrequentistDesignSpecInput;
}

export interface PowerResponseInput {
	/** @maxItems 150 */
	analyses: MetricPowerAnalysisInput[];
}

export interface PowerResponseOutput {
	/** @maxItems 150 */
	analyses: MetricPowerAnalysisOutput[];
}

export type PreassignedFrequentistExperimentSpecInputExperimentType =
	(typeof PreassignedFrequentistExperimentSpecInputExperimentType)[keyof typeof PreassignedFrequentistExperimentSpecInputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreassignedFrequentistExperimentSpecInputExperimentType = {
	freq_preassigned: "freq_preassigned",
} as const;

export type PreassignedFrequentistExperimentSpecInputDesignUrl = string | null;

export type PreassignedFrequentistExperimentSpecInputClusterKey = string | null;

export type PreassignedFrequentistExperimentSpecInputDesiredN = number | null;

export interface PreassignedFrequentistExperimentSpecInput {
	experiment_type: PreassignedFrequentistExperimentSpecInputExperimentType;
	/** @maxLength 100 */
	experiment_name: string;
	/** @maxLength 2000 */
	description: string;
	design_url?: PreassignedFrequentistExperimentSpecInputDesignUrl;
	start_date: string;
	end_date: string;
	/**
	 * @minItems 2
	 * @maxItems 20
	 */
	arms: Arm[];
	/** @maxLength 100 */
	table_name: string;
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	primary_key: string;
	cluster_key?: PreassignedFrequentistExperimentSpecInputClusterKey;
	/** @maxItems 150 */
	strata: Stratum[];
	/**
	 * @minItems 1
	 * @maxItems 150
	 */
	metrics: DesignSpecMetricRequest[];
	/** @maxItems 20 */
	filters: FilterInput[];
	desired_n?: PreassignedFrequentistExperimentSpecInputDesiredN;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	power?: number;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	alpha?: number;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	fstat_thresh?: number;
}

export type PreassignedFrequentistExperimentSpecOutputExperimentType =
	(typeof PreassignedFrequentistExperimentSpecOutputExperimentType)[keyof typeof PreassignedFrequentistExperimentSpecOutputExperimentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreassignedFrequentistExperimentSpecOutputExperimentType = {
	freq_preassigned: "freq_preassigned",
} as const;

export type PreassignedFrequentistExperimentSpecOutputDesignUrl = string | null;

export type PreassignedFrequentistExperimentSpecOutputClusterKey =
	| string
	| null;

export type PreassignedFrequentistExperimentSpecOutputDesiredN = number | null;

export interface PreassignedFrequentistExperimentSpecOutput {
	experiment_type: PreassignedFrequentistExperimentSpecOutputExperimentType;
	/** @maxLength 100 */
	experiment_name: string;
	/** @maxLength 2000 */
	description: string;
	design_url?: PreassignedFrequentistExperimentSpecOutputDesignUrl;
	start_date: string;
	end_date: string;
	/**
	 * @minItems 2
	 * @maxItems 20
	 */
	arms: Arm[];
	/** @maxLength 100 */
	table_name: string;
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	primary_key: string;
	cluster_key?: PreassignedFrequentistExperimentSpecOutputClusterKey;
	/** @maxItems 150 */
	strata: Stratum[];
	/**
	 * @minItems 1
	 * @maxItems 150
	 */
	metrics: DesignSpecMetricRequest[];
	/** @maxItems 20 */
	filters: FilterOutput[];
	desired_n?: PreassignedFrequentistExperimentSpecOutputDesiredN;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	power?: number;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	alpha?: number;
	/**
	 * @minimum 0
	 * @maximum 1
	 */
	fstat_thresh?: number;
}

export type PriorTypes = (typeof PriorTypes)[keyof typeof PriorTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PriorTypes = {
	beta: "beta",
	normal: "normal",
} as const;

export type PropertyValueTypes =
	| StrictInt
	| StrictFloat
	| string
	| boolean
	| null;

export type RedshiftDsnType =
	(typeof RedshiftDsnType)[keyof typeof RedshiftDsnType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RedshiftDsnType = {
	redshift: "redshift",
} as const;

export type RedshiftDsnPassword = RevealedStr | Hidden;

export type RedshiftDsnSearchPath = string | null;

export interface RedshiftDsn {
	type: RedshiftDsnType;
	host: string;
	/**
	 * @minimum 1024
	 * @maximum 65535
	 */
	port: number;
	user: string;
	password: RedshiftDsnPassword;
	dbname: string;
	search_path: RedshiftDsnSearchPath;
}

export type Relation = (typeof Relation)[keyof typeof Relation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Relation = {
	includes: "includes",
	excludes: "excludes",
	between: "between",
} as const;

export interface RevealedStr {
	type?: "revealed";
	value: string;
}

export interface SetConnectionToTurnRequest {
	/** @minLength 335 */
	turn_api_token: string;
}

export type SetTurnArmJourneyMappingRequestArmToJourneys = {
	[key: string]: string;
};

export interface SetTurnArmJourneyMappingRequest {
	arm_to_journeys: SetTurnArmJourneyMappingRequestArmToJourneys;
}

export type SnapshotDetailsAnyOf = { [key: string]: unknown };

export type SnapshotDetails = SnapshotDetailsAnyOf | null;

export type SnapshotData = ExperimentAnalysisResponse | null;

export interface Snapshot {
	experiment_id: string;
	id: string;
	status: SnapshotStatus;
	details: SnapshotDetails;
	created_at: string;
	updated_at: string;
	data: SnapshotData;
}

export type SnapshotStatus =
	(typeof SnapshotStatus)[keyof typeof SnapshotStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SnapshotStatus = {
	success: "success",
	running: "running",
	failed: "failed",
} as const;

export type StopAssignmentReason =
	(typeof StopAssignmentReason)[keyof typeof StopAssignmentReason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StopAssignmentReason = {
	preassigned: "preassigned",
	end_date: "end_date",
	manual: "manual",
	target_n: "target_n",
} as const;

export type StrataStrataValue = string | null;

export interface Strata {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
	strata_value?: StrataStrataValue;
}

export interface Stratum {
	/** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
	field_name: string;
}

export type StrictFloat = number | null;

export type StrictInt = number | null;

export type TableDeletedType =
	(typeof TableDeletedType)[keyof typeof TableDeletedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableDeletedType = {
	table_deleted: "table_deleted",
} as const;

export interface TableDeleted {
	type: TableDeletedType;
	table_name: string;
}

export type TableDiff = ColumnDeleted | FieldChangedType | TableDeleted;

export type TurnConfigResponseArmJourneyMap = { [key: string]: string };

export interface TurnConfigResponse {
	experiment_id: string;
	experiment_name: string;
	arm_journey_map: TurnConfigResponseArmJourneyMap;
}

export type UpdateArmRequestName = string | null;

export type UpdateArmRequestDescription = string | null;

export interface UpdateArmRequest {
	name?: UpdateArmRequestName;
	description?: UpdateArmRequestDescription;
}

export interface UpdateBanditArmOutcomeRequest {
	outcome: number;
}

export type UpdateDatasourceRequestName = string | null;

export type UpdateDatasourceRequestDsn = DsnInput | null;

export interface UpdateDatasourceRequest {
	name?: UpdateDatasourceRequestName;
	dsn?: UpdateDatasourceRequestDsn;
}

export type UpdateExperimentRequestName = string | null;

export type UpdateExperimentRequestDescription = string | null;

export type UpdateExperimentRequestDesignUrl = string | null;

export type UpdateExperimentRequestStartDate = string | null;

export type UpdateExperimentRequestEndDate = string | null;

export type UpdateExperimentRequestImpact = Impact | null;

export type UpdateExperimentRequestDecision = string | null;

export interface UpdateExperimentRequest {
	name?: UpdateExperimentRequestName;
	description?: UpdateExperimentRequestDescription;
	design_url?: UpdateExperimentRequestDesignUrl;
	start_date?: UpdateExperimentRequestStartDate;
	end_date?: UpdateExperimentRequestEndDate;
	impact?: UpdateExperimentRequestImpact;
	decision?: UpdateExperimentRequestDecision;
}

export type UpdateOrganizationRequestName = string | null;

export interface UpdateOrganizationRequest {
	name?: UpdateOrganizationRequestName;
}

export interface UpdateOrganizationWebhookRequest {
	/** @maxLength 100 */
	name: string;
	/** @maxLength 500 */
	url: string;
}

export type UpdateParticipantsTypeRequestParticipantType = string | null;

export type UpdateParticipantsTypeRequestTableName = string | null;

export type UpdateParticipantsTypeRequestFields = FieldDescriptor[] | null;

export interface UpdateParticipantsTypeRequest {
	participant_type?: UpdateParticipantsTypeRequestParticipantType;
	table_name?: UpdateParticipantsTypeRequestTableName;
	fields?: UpdateParticipantsTypeRequestFields;
}

export type UpdateParticipantsTypeResponseTableName = string | null;

export type UpdateParticipantsTypeResponseFields = FieldDescriptor[] | null;

export interface UpdateParticipantsTypeResponse {
	/** @maxLength 100 */
	participant_type: string;
	table_name?: UpdateParticipantsTypeResponseTableName;
	fields?: UpdateParticipantsTypeResponseFields;
}

export interface UserSummary {
	/** @maxLength 64 */
	id: string;
	/** @maxLength 64 */
	email: string;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
	loc: ValidationErrorLocItem[];
	msg: string;
	type: string;
	input?: unknown;
	ctx?: ValidationErrorCtx;
}

export type WebhookSummaryAuthToken = string | null;

export interface WebhookSummary {
	id: string;
	type: string;
	name: string;
	url: string;
	auth_token: WebhookSummaryAuthToken;
}

export interface XHTTPValidationError {
	detail: XValidationError[];
}

export type XValidationErrorLocItem = string | number;

export interface XValidationError {
	loc: XValidationErrorLocItem[];
	msg: string;
	type: string;
}

export type DeleteSnapshotParams = {
	allow_missing?: boolean;
};

export type ListSnapshotsParams = {
	status?: SnapshotStatus[] | null;
	/**
	 * @minimum 1
	 * @maximum 100
	 */
	page_size?: number;
	page_token?: string | null;
	/**
	 * @minimum 0
	 */
	skip?: number;
};

export type DeleteWebhookFromOrganizationParams = {
	allow_missing?: boolean;
};

export type ListOrganizationEventsParams = {
	/**
	 * @minimum 1
	 * @maximum 100
	 */
	page_size?: number;
	page_token?: string | null;
	/**
	 * @minimum 0
	 */
	skip?: number;
};

export type RemoveMemberFromOrganizationParams = {
	allow_missing?: boolean;
};

export type CreateDatasourceParams = {
	connectivity_check?: boolean;
};

export type InspectDatasourceParams = {
	refresh?: boolean;
};

export type InspectTableInDatasourceParams = {
	refresh?: boolean;
};

export type DeleteDatasourceParams = {
	allow_missing?: boolean;
};

export type InspectParticipantTypesParams = {
	refresh?: boolean;
	expensive?: boolean;
};

export type DeleteParticipantParams = {
	allow_missing?: boolean;
};

export type DeleteApiKeyParams = {
	allow_missing?: boolean;
};

export type CreateExperimentParams = {
	stratify_on_metrics?: boolean;
};

export type AnalyzeExperimentParams = {
	baseline_arm_id?: string | null;
};

export type DeleteExperimentParams = {
	allow_missing?: boolean;
};

export type GetOrganizationTurnConnectionParams = {
	allow_missing?: boolean;
};

export type DeleteTurnConnectionFromOrganizationParams = {
	allow_missing?: boolean;
};

export type DeleteTurnArmJourneyMappingParams = {
	allow_missing?: boolean;
};
